export const CART_SET_VISIBLE = 'CART:SET_VISIBLE';
export const CART_SET_ITEMS = 'CART:SET_ITEMS';
export const CART_INCREMENT_ITEM = 'CART:CART_INCREMENT_ITEM';
export const CART_DECREMENT_ITEM = 'CART:CART_DECREMENT_ITEM';
export const CART_REMOVE_ITEM = 'CART:CART_REMOVE_ITEM';
export const CART_ADD_FOOD_ITEM = 'CART:CART_ADD_FOOD_ITEM';
export const CART_SET_TOTAL = 'CART:SET_TOTAL';
export const PRELOADER_SET_PRELOADER = 'PRELOADER:SET_PRELOADER';
